import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  String _locale = 'sw'; // Default is Swahili for Tanzanian bodaboda riders

  String get locale => _locale;

  LanguageProvider() {
    _loadLocale();
  }

  Future<void> _loadLocale() async {
    final prefs = await SharedPreferences.getInstance();
    _locale = prefs.getString('chapgo_locale') ?? 'sw';
    notifyListeners();
  }

  Future<void> setLocale(String locale) async {
    if (locale == _locale) return;
    _locale = locale;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('chapgo_locale', locale);
    notifyListeners();
  }

  String translate(String key) {
    if (_locale == 'sw') {
      return _swTranslations[key] ?? _enTranslations[key] ?? key;
    } else {
      return _enTranslations[key] ?? _swTranslations[key] ?? key;
    }
  }

  static const Map<String, String> _enTranslations = {
    // General / Auth
    'login': 'Login',
    'sign_out': 'Sign Out',
    'welcome': 'Welcome',
    'language': 'Language',
    'sacco_membership': 'SACCO Membership',
    'sacco_select': 'Select SACCO',
    'near_you': 'Near you',
    'no_sacco_assigned': 'No SACCO selected',
    'swahili': 'Swahili',
    'english': 'English',
    'error': 'Error',
    'success': 'Success',
    // Login Screen Keys
    'phone_number_tab': 'Phone Number',
    'password_tab': 'Password',
    'login_with_otp': 'Login with OTP',
    'otp_sms_note': 'We will send you an OTP by SMS',
    'phone_field': 'Phone Number',
    'phone_hint': '712345678 or 0712345678',
    'send_otp': 'Send OTP',
    'send_otp_btn': 'Send OTP by SMS',
    'login_with_password': 'Login with Password',
    'password_login_note': 'Use phone number or email and password',
    'email_phone_field': 'Phone Number or Email',
    'email_phone_hint': '+2557... or admin@chapgo.co.tz',
    'password_field': 'Password',
    'login_btn': 'Login',
    'no_account': 'Don\'t have an account? ',
    'register_now': 'Register now',
    'login_success': 'Login successful',
    'login_failed': 'Login failed',
    'fill_all_fields': 'Please fill in all details',
    'invalid_phone': 'Invalid phone number. Example: 0712345678',
    'otp_sent_success': 'OTP has been sent to your number',
    // Register Screen Keys
    'register_title': 'Register',
    'register_heading': 'Create Driver Account',
    'register_subheading': 'Fill in your details below',
    'full_name_field': 'Full Name',
    'nida_field': 'NIDA Number (20 digits)',
    'plate_field': 'Vehicle Plate',
    'password_create_field': 'Password (Create password)',
    'vehicle_type_field': 'Vehicle Type',
    'consent_checkbox': 'I consent to the processing of my personal data in accordance with the Chapgo privacy policy',
    'register_btn': 'Register',
    'change_phone_name': 'Change Number/Name',
    'name_min_chars': 'Name must be at least 3 characters',
    'otp_digit_count': 'Please enter OTP (6 digits)',
    'nida_digit_count': 'NIDA must be 20 digits',
    'plate_invalid': 'Invalid vehicle plate. Example: T123ABC',
    'password_min_chars': 'Password must be at least 6 characters',
    'consent_warning': 'Please agree to data processing consent',
    'register_success': 'Registration successful!',
    'register_failed': 'Registration failed',
    // Driver Home
    'driver_title': 'Chapgo Driver',
    'overview': 'Overview',
    'profile': 'My Profile',
    'qr_code': 'My QR Code',
    'boda_score': 'Boda Score',
    'loans': 'My Loans',
    'income': 'Income',
    'expenses': 'Expenses',
    'total_income': 'Total Income',
    'total_expenses': 'Total Expenses',
    'net_balance': 'Net Cashflow',
    'recent_activities': 'Recent Cashflow',
    'no_activities': 'No cashflow logged yet',
    // Cashflow panel
    'add_income': 'Add Income',
    'add_expense': 'Add Expense',
    'income_source': 'Income Source',
    'expense_category': 'Expense Category',
    'amount': 'Amount (TSh)',
    'description': 'Description (Optional)',
    'submit': 'Save',
    'fuel': 'Fuel',
    'maintenance': 'Repair & Service',
    'fare': 'Passenger Fare',
    'food': 'Food & Personal',
    'sacco': 'SACCO Contribution',
    'other': 'Other',
    // Repayment / Loans / Smart Advisor
    'calculator': 'Repayment Calculator',
    'daily_income_predict': 'Estimated Daily Income',
    'daily_expense_predict': 'Estimated Daily Expense',
    'repayment_capacity': 'Repayment Capacity',
    'safe_daily_pay': 'Safe Daily Repayment',
    'safe_loan_advice': 'Based on your cashflow, you can safely afford a daily loan payment of up to:',
    'credit_limit': 'Your Current Credit Limit',
    'bronze_tier': 'Bronze Tier',
    'silver_tier': 'Silver Tier',
    'gold_tier': 'Gold Tier',
    'platinum_tier': 'Platinum Tier',
    'repayment_advisor': 'Repayment Capacity Advisor',
    'safe_repayment_levels': 'Safe Repayment Levels',
    'daily_cash_remaining': 'Daily Cash remaining after expenses',
    'super_safe_level': 'Super Safe (30%)',
    'moderate_level': 'Moderate (50%)',
    'risky_level': 'Risky (70%+)',
    'super_safe_desc': 'Very safe amount. Highly recommended to handle slow business days.',
    'moderate_desc': 'Standard payment level. Needs consistent daily income.',
    'risky_desc': 'High risk. Can put financial strain if you have emergencies or illness.',
    'repayment_recomm': 'Our recommendation for you',
    'score_not_active': 'Your Boda Score will activate after 30 days of membership and regular fuel scans. Keep scanning!',
    'days_active_label': 'Days active',
    'scan_history_label': 'Scans logged',
    'repayment_discipline': 'SACCO repayment rate',
    'score_breakdown': 'Boda Score Breakdown',
    'days_member_label': 'Membership duration',
    'daily_avg_scans': 'Average scans per day',
    'income_consistency_label': 'Income Consistency',
    'attendance_regularity_label': 'Attendance Regularity',
    'hours_discipline_label': 'Hours Discipline',
    'fuel_efficiency_label': 'Fuel Efficiency',
    'sacco_compliance_label': 'SACCO Compliance',
    'boda_score_tips_title': 'How to Improve Boda Score',
    'tip_income_title': 'Income Consistency',
    'tip_income_desc': 'Log all your passenger fares and deliveries in "My Money" daily. Consistent daily logs build financial trust.',
    'tip_attendance_title': 'Attendance Regularity',
    'tip_attendance_desc': 'Make fuel scans regularly at verified stations. Aim to scan fuel on at least 15-20 days each month.',
    'tip_hours_title': 'Hours Discipline',
    'tip_hours_desc': 'Scan fuel during your regular work hours. Consistent daily shifts show predictable business operation.',
    'tip_efficiency_title': 'Fuel Efficiency',
    'tip_efficiency_desc': 'Report accurate daily earnings. If missing, the engine estimates earnings from scans. Keep operations efficient!',
    'tip_sacco_title': 'SACCO Compliance',
    'tip_sacco_desc': 'Pay your loan installments on time and keep active savings in your SACCO to unlock premium tiers.',
    'improve_score_hint': 'Action steps to unlock higher loan limits:',
    'points_out_of': 'out of 200 pts',
    'thin_file_note': 'Your score is under evaluation (\'NEW\') because you have been registered for less than 30 days or have under 20 scans. Keep scanning to activate your score!',
    'boda_score_desc': 'Boda Score helps local bank partners assess your creditworthiness. A higher score means larger loans and cheaper rates.',
    'btn_go_to_money': 'Record Cashflow',
    'btn_go_to_saccos': 'Go to My SACCO',
    'recalculate_score_btn': 'Refresh My Score',
    'score_recalculated_success': 'Score refreshed successfully!',
    'apply_loan_btn': 'Apply for a Loan',
    'no_active_loans': 'No active or pending loans currently',
    'eligible_loan_range': 'Your Eligible Loan Limit',
    'eligible_products': 'Qualified Loan Products',
    'loan_id_label': 'Loan ID',
    'loan_purpose_label': 'Purpose',
    'loan_amount_label': 'Amount',
    'loan_status_label': 'Status',
    'loan_payment_label': 'Monthly Payment',
    'loan_term_label': 'Term',
    'loan_date_label': 'Application Date',
    'custom_category': 'Custom Reason / Category',
    'custom_category_hint': 'e.g., School Fees, Spare Parts',
    'loan_purpose_field': 'Loan Purpose',
    'loan_term_field': 'Term (Months)',
    'bank_partner_field': 'Bank Partner',
    'phone_number_label': 'Phone Number',
    'otp_code_label': 'OTP Verification Code',
    'request_otp_btn': 'Request Verification Code',
    'passport_number_field': 'Passport Number',
    'passport_hint': 'e.g. TZ123456',
    'emergency_contact_name_field': 'Emergency Contact Name',
    'emergency_name_hint': 'Full Name',
    'emergency_contact_phone_field': 'Emergency Contact Phone',
    'emergency_phone_hint': 'e.g. +255...',
    'residential_address_field': 'Residential Address',
    'address_hint': 'House number, Street, Ward',
    'verification_details': 'Verification Details',
    'optional_label': 'Optional',
    'submit_loan_btn': 'Submit Loan Application',
    'loan_applied_msg': 'Loan application submitted successfully!',
    'loan_failed_msg': 'Loan application failed',
    'otp_sent_msg': 'OTP verification code sent!',
    // Sidebar / Menus
    'menu_sacco': 'SACCO & Loans',
    'menu_apply_loan': 'Apply for Loan',
    'menu_loan_list': 'My Loan Applications',
    'menu_stations': 'Fuel Stations',
    'menu_stations_map': 'Live Stations Map',
    'menu_stations_list': 'Stations Directory',
    'menu_report': 'Report & Evaluation',
    // Notifications
    'notifications_title': 'Notifications',
    'mark_all_read': 'Mark All as Read',
    'no_notifications': 'No notifications yet',
    // Date Filters & Pagination
    'filter_date': 'Date Filter',
    'filter_amount': 'Min Amount (TSh)',
    'preset_today': 'Today',
    'preset_yesterday': 'Yesterday',
    'preset_weekly': 'Weekly (7 Days)',
    'preset_monthly': 'Monthly (30 Days)',
    'preset_6months': '6 Months (180 Days)',
    'preset_yearly': 'Yearly (365 Days)',
    'preset_all': 'All Time',
    'view_more': 'View More',
    'page_label': 'Page',
    // Loan List Tabs
    'tab_success': 'Success / Active',
    'tab_pending': 'Pending Review',
    'tab_rejected': 'Rejected / Denied',
    // Report Screen
    'eval_title': 'Usage & Loan Report',
    'eval_usage_score': 'System Utilization Score',
    'eval_usage_desc': 'Your rating of how actively you scan fuel and log cashflow. High usage improves credit tier!',
    'eval_credit_tips': 'Loan Qualification Tips',
    'eval_tip_1': 'Scan your QR code for every fuel fill to log activity.',
    'eval_tip_2': 'Keep your cashflow records updated daily for better credit limits.',
    'eval_tip_3': 'Maintain repayments to your SACCO to unlock Gold and Platinum tiers.',
    'station_select_title': 'Fill Oil Station Selector',
    'station_select_confirm': 'Select this station to refill oil',
    'station_selected': 'REFUEL CHOICE CONFIRMED',
    'station_select_btn': 'Refuel Here',
    'standards': 'Sacco Standards',
    'min_boda_score': 'Min Boda Score',
    'min_savings_balance_tsh': 'Min Savings Balance (TSh)',
    'max_loan_limit_multiplier': 'Loan Limit Multiplier',
    'update_standards': 'Update Sacco Standards',
    'standards_updated': 'Sacco standards updated successfully',
    'system_drivers_search': 'Search System Drivers',
    'search_system_drivers_hint': 'Search by Name, Phone, Plate or ID',
    'invite_driver_loan': 'Invite to Apply for Loan',
    'recruit_driver': 'Add as Sacco Member',
    'driver_details': 'Driver Analysis & Profile',
    'income_expense_summary': 'Cashflow Performance',
    'loan_history': 'Loan Applications History',
    'record_repayment': 'Record Loan Repayment',
    'repayment_amount': 'Repayment Amount',
    'repayment_method': 'Repayment Method',
    'repayment_success': 'Repayment recorded successfully!',
    'remaining_balance': 'Remaining Balance',
    'total_repaid': 'Total Repaid',
    'repayment_frequency': 'Repayment Frequency',
    'daily': 'Daily',
    'weekly': 'Weekly',
    'monthly': 'Monthly',
    'custom': 'Custom (Days)',
    'custom_days': 'Custom Repayment Interval (Days)',
    'enter_custom_days': 'Please enter number of days',
    'missed_payments': 'Missed Payments',
    'missed_payments_count': 'Missed Payments Count',
    'history_repayment': 'Repayment History',
    'increment_missed': 'Increment Missed',
    'decrement_missed': 'Decrement Missed',
    'days_label': 'Days',
    // Driver dark nav
    'nav_home': 'Home',
    'nav_money': 'Money',
    'nav_history': 'History',
    'nav_scan': 'Scan',
    'nav_credit': 'Credit',
    'nav_profile': 'Profile',
    // Credit (AI) screen
    'credit_title': 'RIDER PROFILE FOR BANK REVIEW',
    'credit_subtitle': 'AI credit assessment based on your fuel scans & cashflow',
    'credit_run': 'Run Credit Analysis',
    'credit_recommendation': 'Recommendation',
    'credit_loan_limit': 'Recommended Loan Limit',
    'credit_interest': 'Indicative Interest',
    'credit_dti': 'Debt-to-Income Ratio',
    'credit_monthly_income': 'Est. Monthly Income',
    'credit_max_repayment': 'Max Affordable Repayment',
    'credit_risk_factors': 'Risk Factors',
    'credit_strengths': 'Strengths',
    'credit_conditions': 'Conditions',
    'credit_summary': 'Summary',
    'credit_approve': 'APPROVE',
    'credit_conditional': 'CONDITIONAL',
    'credit_decline': 'DECLINE',
    'credit_none_yet': 'Tap "Run Credit Analysis" to generate your bank-ready profile.',
    'scan_today_title': 'Today\u2019s Scans',
    'your_status': 'Your Status',
    'documents': 'Documents',
    'recent_scans': 'Recent Scans',
    'see_all': 'See All',
    'financial_services': 'Financial Services',
    'loan_prequal': 'Loan Pre-Qualification',
    'days_active_short': 'Days Active',
    'scan_count_label': 'Total Scans',
    'litres_30d': 'Litres (30d)',
    'fuel_spent_30d': 'Fuel Spent (30d)',
    'registration_complete': 'Registration Complete',
    'account_active': 'Active',
    'account_pending': 'Pending',
    'savings_balance': 'Savings Balance',
    'dues_status': 'Dues Status',
    'current': 'Current',
    'eligible_now': 'Eligible now',
    'days_until_eligible': 'days until eligible (90-day minimum)',
    'complete_label': 'complete',
    'my_money_subtitle': 'Track your spending to build a stronger Boda Score',
    'cashflow_30d': '30-DAY CASHFLOW',
    'est_income': 'Income (reported)',
    'reported_spending': 'Reported Spending',
    'estimated_surplus': 'Estimated Surplus',
    'why_track': 'Why Track Spending?',
    'why_track_desc': 'Banks need to see that you earn more than you spend before approving a loan. Track regularly to unlock larger loans at lower interest.',
    'this_month_spending': 'This Month\'s Spending',
    'add': 'Add',
    'credit_profile': 'Credit Profile',
    'what_bank_sees': 'WHAT THE BANK SEES',
    'no_spending_yet': 'No spending logged yet',
    'no_scans_yet': 'No fuel scans yet',
    'scan_history_title': 'Fuel Scan History',
    'totals_30d': '30-Day Totals',
    'sign_out_confirm': 'Sign Out',
    'data_privacy': 'Data & Privacy',
    'view_my_data': 'View My Data',
    'view_my_data_desc': 'See all data Chapgo holds about you',
    'menu_qr': 'My QR Code',
    // ChapDeliver (Delivery)
    'deliver': 'Deliver',
    'delivery_title': 'ChapDeliver™',
    'delivery_subtitle': 'E-Commerce Trust & Last-Mile Delivery',
    'delivery_coming_soon': 'COMING SOON',
    'delivery_coming_soon_desc': 'Phase 3+ Module — Architected now, deployed after Chapgo core proves the model',
    'delivery_planned_features': 'PLANNED FEATURES',
    'delivery_feat_escrow': 'Escrow Payments',
    'delivery_feat_escrow_desc': 'Buyer funds held safely until delivery is confirmed via QR scan',
    'delivery_feat_pricing': 'Dynamic Pricing',
    'delivery_feat_pricing_desc': 'Uber-style distance-based delivery fees with transparent breakdown',
    'delivery_feat_seller_score': 'Seller Score',
    'delivery_feat_seller_score_desc': 'Trust badges — only verified transaction ratings count',
    'delivery_feat_tracking': 'Live Tracking',
    'delivery_feat_tracking_desc': 'Real-time GPS tracking from pickup to delivery',
    'delivery_feat_dispute': 'Dispute Resolution',
    'delivery_feat_dispute_desc': '24-hour resolution with photo evidence',
    'delivery_feat_pindrop': 'Pin-Drop Addresses',
    'delivery_feat_pindrop_desc': 'GPS pin-drop with landmark descriptions — no postal address needed',
    'delivery_how_it_works': 'HOW IT WORKS',
    'delivery_step_1': 'Seller creates a listing with the item price',
    'delivery_step_2': 'Buyer deposits funds into ChapPesa Escrow',
    'delivery_step_3': 'Chapgo rider picks up and delivers the item',
    'delivery_step_4': 'Buyer scans the QR code to confirm receipt',
    'delivery_step_5': 'Funds are released to the seller and the rider',
    'delivery_regulatory': 'REGULATORY DEPENDENCIES',
    'delivery_regulatory_desc': 'Escrow requires a BoT payment licence or a licensed partner. Recommended via the BoT Fintech Regulatory Sandbox (GN 540/2024). Seller verification requires the NIDA API. All data must comply with PDPA 2022 and the Electronic Transactions Act 2015.',
    'delivery_register_interest': 'Register My Interest',
    'delivery_interest_recorded': 'Thanks! We\'ll notify you when ChapDeliver launches.',
  };

  static const Map<String, String> _swTranslations = {
    // General / Auth
    'login': 'Ingia',
    'sign_out': 'Ondoka',
    'welcome': 'Karibu',
    'language': 'Lugha',
    'sacco_membership': 'Uanachama wa SACCO',
    'sacco_select': 'Chagua SACCO',
    'near_you': 'Karibu nawe',
    'no_sacco_assigned': 'Hakuna SACCO iliyochaguliwa',
    'swahili': 'Kiswahili',
    'english': 'Kiingereza',
    'error': 'Itilafu',
    'success': 'Umefanikiwa',
    // Login Screen Keys
    'phone_number_tab': 'Namba ya Simu',
    'password_tab': 'Nenosiri',
    'login_with_otp': 'Ingia kwa OTP',
    'otp_sms_note': 'Tutakutumia OTP kwa SMS',
    'phone_field': 'Namba ya simu',
    'phone_hint': '712345678 au 0712345678',
    'send_otp': 'Tuma OTP',
    'send_otp_btn': 'Tuma OTP kwa SMS',
    'login_with_password': 'Ingia kwa nenosiri',
    'password_login_note': 'Tumia namba ya simu au barua pepe na nenosiri',
    'email_phone_field': 'Namba ya Simu au Barua pepe',
    'email_phone_hint': '+2557... au admin@chapgo.co.tz',
    'password_field': 'Nenosiri',
    'login_btn': 'Ingia',
    'no_account': 'Huna akaunti? ',
    'register_now': 'Sajili sasa',
    'login_success': 'Ingia imefanikiwa',
    'login_failed': 'Ingia imeshindikana',
    'fill_all_fields': 'Tafadhali jaza taarifa zote',
    'invalid_phone': 'Namba ya simu si sahihi. Mfano: 0712345678',
    'otp_sent_success': 'OTP imetumwa kwa namba yako',
    // Register Screen Keys
    'register_title': 'Sajili',
    'register_heading': 'Unda akaunti ya Driver',
    'register_subheading': 'Jaza taarifa zako hapa chini',
    'full_name_field': 'Jina kamili',
    'nida_field': 'Namba ya NIDA (tarakimu 20)',
    'plate_field': 'Namba ya gari',
    'password_create_field': 'Nenosiri (Tengeneza password)',
    'vehicle_type_field': 'Aina ya gari',
    'consent_checkbox': 'Nakubali usindikaji wa data yangu binafsi kwa mujibu wa sera ya faragha ya Chapgo',
    'register_btn': 'Sajili',
    'change_phone_name': 'Badili Namba/Jina',
    'name_min_chars': 'Jina lazima liwe angalau herufi 3',
    'otp_digit_count': 'Tafadhali weka namba ya OTP (tarakimu 6)',
    'nida_digit_count': 'NIDA ina tarakimu 20',
    'plate_invalid': 'Namba ya gari si sahihi. Mfano: T123ABC',
    'password_min_chars': 'Nenosiri lazima liwe na angalau herufi 6',
    'consent_warning': 'Tafadhali kubali masharti ya usindikaji wa data',
    'register_success': 'Usajili umefanikiwa!',
    'register_failed': 'Usajili umeshindikana',
    // Driver Home
    'driver_title': 'Dereva Chapgo',
    'overview': 'Muhtasari',
    'profile': 'Taarifa Zangu',
    'qr_code': 'QR Code Yangu',
    'boda_score': 'Boda Score',
    'loans': 'Mikopo Yangu',
    'income': 'Kipato',
    'expenses': 'Matumizi',
    'total_income': 'Jumla ya Kipato',
    'total_expenses': 'Jumla ya Matumizi',
    'net_balance': 'Baki la Pesa',
    'recent_activities': 'Miamala ya Hivi Karibuni',
    'no_activities': 'Bado hujaweka miamala yoyote',
    // Cashflow panel
    'add_income': 'Weka Kipato',
    'add_expense': 'Weka Matumizi',
    'income_source': 'Chanzo cha Kipato',
    'expense_category': 'Aina ya Matumizi',
    'amount': 'Kiasi (TSh)',
    'description': 'Maelezo (Si lazima)',
    'submit': 'Hifadhi',
    'fuel': 'Mafuta ya Chombo',
    'maintenance': 'Matengenezo (Spana)',
    'fare': 'Nauli ya Abiria',
    'food': 'Chakula & Binafsi',
    'sacco': 'Mchango wa SACCO',
    'other': 'Mengineyo',
    // Repayment / Loans / Smart Advisor
    'calculator': 'Kikokotoo cha Marejesho',
    'daily_income_predict': 'Kipato cha Siku (Kadirio)',
    'daily_expense_predict': 'Matumizi ya Siku (Kadirio)',
    'repayment_capacity': 'Uwezo wa Kulipa',
    'safe_daily_pay': 'Malipo Salama kwa Siku',
    'safe_loan_advice': 'Kulingana na mzunguko wako wa pesa, unaweza kumudu marejesho ya mikopo ya hadi:',
    'credit_limit': 'Kikomo chako cha Mkopo kwa Sasa',
    'bronze_tier': 'Kiwango cha Bronze',
    'silver_tier': 'Kiwango cha Silver',
    'gold_tier': 'Kiwango cha Gold',
    'platinum_tier': 'Kiwango cha Platinum',
    'repayment_advisor': 'Kikokotoo cha Uwezo wa Kulipa',
    'safe_repayment_levels': 'Viwango Salama vya Marejesho',
    'daily_cash_remaining': 'Kipato kilichobaki kila siku baada ya matumizi',
    'super_safe_level': 'Salama Kabisa (30%)',
    'moderate_level': 'Kawaida (50%)',
    'risky_level': 'Ina Hatari (70%+)',
    'super_safe_desc': 'Kiwango salama kabisa kisichokupa shinikizo hata siku za kazi zikiwa ngumu.',
    'moderate_desc': 'Kiwango cha kawaida. Kinahitaji mzunguko mzuri na nidhamu ya kazi.',
    'risky_desc': 'Kiwango cha juu cha hatari. Kinaweza kukupa shida kukiwa na dharura au ugonjwa.',
    'repayment_recomm': 'Ushauri wetu kwako',
    'score_not_active': 'Alama zako zitaanza kuhesabiwa baada ya siku 30 tangu kujiunga na kuscan mafuta. Endelea kuscan!',
    'days_active_label': 'Siku ambazo umekuwa hai',
    'scan_history_label': 'Miamala ya scan',
    'repayment_discipline': 'Nidhamu ya marejesho ya SACCO',
    'score_breakdown': 'Mchanganuo wa Boda Score',
    'days_member_label': 'Muda tangu ujiunge',
    'daily_avg_scans': 'Kiwango cha scan kwa siku',
    'income_consistency_label': 'Uthabiti wa Kipato',
    'attendance_regularity_label': 'Uthabiti wa Mahudhurio',
    'hours_discipline_label': 'Nidhamu ya Masaa ya Kazi',
    'fuel_efficiency_label': 'Ufanisi wa Mafuta',
    'sacco_compliance_label': 'Uzingatiaji wa SACCO',
    'boda_score_tips_title': 'Jinsi ya Kuongeza Boda Score',
    'tip_income_title': 'Uthabiti wa Kipato',
    'tip_income_desc': 'Rekodi kipato na matumizi yako yote kila siku kwenye sehemu ya "Pesa". Kumbukumbu za kila siku zinajenga uaminifu wa fedha.',
    'tip_attendance_title': 'Uthabiti wa Mahudhurio',
    'tip_attendance_desc': 'Scan mafuta katika vituo vilivyothibitishwa kila siku. Lengo ni kuscan angalau siku 15-20 kwa mwezi.',
    'tip_hours_title': 'Nidhamu ya Masaa ya Kazi',
    'tip_hours_desc': 'Scan mafuta wakati ule ule wa masaa yako ya kazi. Hii inaonyesha ratiba thabiti na inayotabirika ya biashara yako.',
    'tip_efficiency_title': 'Ufanisi wa Mafuta',
    'tip_efficiency_desc': 'Rekodi mapato sahihi kila siku. Usiporekodisha, mfumo unakadiria mapato kutoka kwenye scan. Dumisha ufanisi!',
    'tip_sacco_title': 'Uzingatiaji wa SACCO',
    'tip_sacco_desc': 'Lipea marejesho ya mikopo kwa wakati na weka akiba ya mara kwa mara kwenye SACCO yako ili kufungua viwango vya juu.',
    'improve_score_hint': 'Hatua za kuchukua ili kuongeza kikomo chako cha mkopo:',
    'points_out_of': 'kati ya alama 200',
    'thin_file_note': 'Alama zako zipo kwenye tathmini (\'NEW\') kwa sababu umejiunga chini ya siku 30 au umescan chini ya mara 20. Endelea kuscan ili kuwasha alama zako!',
    'boda_score_desc': 'Boda Score inasaidia benki washirika kutathmini uwezo wako vya kukopa. Alama kubwa maana yake mikopo mikubwa na riba ndogo.',
    'btn_go_to_money': 'Rekodi Mzunguko wa Pesa',
    'btn_go_to_saccos': 'Nenda kwenye SACCO yangu',
    'recalculate_score_btn': 'Sasisha Boda Score Yangu',
    'score_recalculated_success': 'Boda Score imesasishwa kwa mafanikio!',
    'apply_loan_btn': 'Omba Mkopo mpya',
    'no_active_loans': 'Huna mkopo wa sasa',
    'eligible_loan_range': 'Uwezo wako wa Kukopa',
    'eligible_products': 'Bidhaa unazostahili',
    'loan_id_label': 'Namba ya Mkopo',
    'loan_purpose_label': 'Aina ya Mkopo',
    'loan_amount_label': 'Kiasi',
    'loan_status_label': 'Hali ya Mkopo',
    'loan_payment_label': 'Kiasi cha Mwezi',
    'loan_term_label': 'Muda wa Mkopo',
    'loan_date_label': 'Tarehe ya Maombi',
    'custom_category': 'Sababu / Kundi Maalum',
    'custom_category_hint': 'Mfano: Ada ya Shule, Vipuri vya Vyombo',
    'loan_purpose_field': 'Lengo la Mkopo',
    'loan_term_field': 'Muda wa Mkopo (Miezi)',
    'bank_partner_field': 'Benki Shirika',
    'phone_number_label': 'Namba ya Simu',
    'otp_code_label': 'Namba ya Uhakiki ya OTP',
    'request_otp_btn': 'Omba Namba ya Uhakiki',
    'passport_number_field': 'Namba ya Pasipoti',
    'passport_hint': 'Mfano: TZ123456',
    'emergency_contact_name_field': 'Jina la Mwasiliani wa Dharura',
    'emergency_name_hint': 'Jina Kamili',
    'emergency_contact_phone_field': 'Simu ya Mwasiliani wa Dharura',
    'emergency_phone_hint': 'Mfano: +255...',
    'residential_address_field': 'Anwani ya Makazi',
    'address_hint': 'Namba ya nyumba, Mtaa, Kata',
    'verification_details': 'Maelezo ya Uhakiki',
    'optional_label': 'Si Lazima',
    'submit_loan_btn': 'Tuma Ombi la Mkopo',
    'loan_applied_msg': 'Ombi la mkopo limetumwa kwa mafanikio!',
    'loan_failed_msg': 'Ombi la mkopo limeshindikana',
    'otp_sent_msg': 'Namba ya uhakiki ya OTP imetumwa!',
    // Sidebar / Menus
    'menu_sacco': 'SACCO & Mikopo',
    'menu_apply_loan': 'Omba Mkopo',
    'menu_loan_list': 'Maombi ya Mikopo',
    'menu_stations': 'Vituo vya Mafuta',
    'menu_stations_map': 'Ramani ya Vituo vya Live',
    'menu_stations_list': 'Orodha ya Vituo',
    'menu_report': 'Ripoti & Tathmini',
    // Notifications
    'notifications_title': 'Arifa',
    'mark_all_read': 'Soma Zote',
    'no_notifications': 'Huna arifa kwa sasa',
    // Date Filters & Pagination
    'filter_date': 'Kichujio cha Tarehe',
    'filter_amount': 'Kiwango cha Chini (TSh)',
    'preset_today': 'Leo',
    'preset_yesterday': 'Jana',
    'preset_weekly': 'Wiki Hii (Siku 7)',
    'preset_monthly': 'Mwezi Huu (Siku 30)',
    'preset_6months': 'Miezi 6 (Siku 180)',
    'preset_yearly': 'Mwaka Huu (Siku 365)',
    'preset_all': 'Muda Wote',
    'view_more': 'Angalia Zaidi',
    'page_label': 'Ukurasa',
    // Loan List Tabs
    'tab_success': 'Imefanikiwa / Hai',
    'tab_pending': 'Inasubiri Uhakiki',
    'tab_rejected': 'Imekataliwa / Ilishindwa',
    // Report Screen
    'eval_title': 'Tathmini ya Mfumo & Mikopo',
    'eval_usage_score': 'Alama ya Matumizi ya Mfumo',
    'eval_usage_desc': 'Tathmini ya jinsi unavyoscan mafuta na kurekodi vipato/matumizi. Matumizi ya juu yanaboresha kikomo chako cha mkopo!',
    'eval_credit_tips': 'Miongozo ya Kufuzu Mikopo',
    'eval_tip_1': 'Scan QR code kila unaponunua mafuta ili kuonyesha mzunguko vya fedha.',
    'eval_tip_2': 'Weka kumbukumbu za vipato na matumizi kila siku ili kuongeza kikomo chako cha mkopo.',
    'eval_tip_3': 'Dumisha nidhamu ya kurejesha mikopo ya SACCO ili kufungua viwango vya Gold na Platinum.',
    'station_select_title': 'Chagua Kituo cha Kujaza Mafuta',
    'station_select_confirm': 'Chagua kituo hiki cha kujaza mafuta',
    'station_distance': 'Umbali',
    'station_selected': 'KUCHAGUA KITUO KUMETHIBITISHWA',
    'station_select_btn': 'Jaza Hapa',
    'standards': 'Kanuni za Sacco',
    'min_boda_score': 'Kiwango cha Chini cha Boda Score',
    'min_savings_balance_tsh': 'Akiba ya Chini Kabisa (TSh)',
    'max_loan_limit_multiplier': 'Kuzidisha Kikomo cha Mkopo',
    'update_standards': 'Sasisha Kanuni za Sacco',
    'standards_updated': 'Kanuni za Sacco zimesasishwa kwa ufanisi',
    'system_drivers_search': 'Tafuta Madereva wa Mfumo',
    'search_system_drivers_hint': 'Tafuta kwa Jina, Simu, Namba ya Chombo au ID',
    'invite_driver_loan': 'Alika kuomba mkopo',
    'recruit_driver': 'Weka Mwanachama wa Sacco',
    'driver_details': 'Uchambuzi na Taarifa za Dereva',
    'income_expense_summary': 'Tathmini ya Mzunguko wa Fedha',
    'loan_history': 'Historia ya Maombi ya Mikopo',
    'record_repayment': 'Rekodi Rejesho la Mkopo',
    'repayment_amount': 'Kiasi cha Rejesho',
    'repayment_method': 'Njia ya Malipo',
    'repayment_success': 'Rejesho limerekodiwa kwa ufanisi!',
    'remaining_balance': 'Baki ya Mkopo',
    'total_repaid': 'Jumla ya Marejesho',
    'repayment_frequency': 'Mzunguko wa Marejesho',
    'daily': 'Kila Siku',
    'weekly': 'Kila Wiki',
    'monthly': 'Kila Mwezi',
    'custom': 'Maalum (Siku)',
    'custom_days': 'Muda wa Kila Malipo (Siku)',
    'enter_custom_days': 'Tafadhali weka idadi ya siku',
    'missed_payments': 'Malipo Yaliyokosa',
    'missed_payments_count': 'Idadi ya Malipo Yaliyokosa',
    'history_repayment': 'Historia ya Marejesho',
    'increment_missed': 'Ongeza Malipo Yaliyokosa',
    'decrement_missed': 'Punguza Malipo Yaliyokosa',
    'days_label': 'Siku',
    // Driver dark nav
    'nav_home': 'Nyumbani',
    'nav_money': 'Pesa',
    'nav_history': 'Historia',
    'nav_scan': 'Skani',
    'nav_credit': 'Mkopo',
    'nav_profile': 'Wasifu',
    // Credit (AI) screen
    'credit_title': 'WASIFU WA DEREVA KWA BENKI',
    'credit_subtitle': 'Tathmini ya mkopo kwa AI kutoka skani za mafuta na mzunguko wa fedha',
    'credit_run': 'Fanya Tathmini ya Mkopo',
    'credit_recommendation': 'Pendekezo',
    'credit_loan_limit': 'Kikomo cha Mkopo Kinachopendekezwa',
    'credit_interest': 'Riba ya Makadirio',
    'credit_dti': 'Uwiano wa Deni kwa Kipato',
    'credit_monthly_income': 'Kipato cha Mwezi (Kadirio)',
    'credit_max_repayment': 'Marejesho ya Juu Unayoweza',
    'credit_risk_factors': 'Sababu za Hatari',
    'credit_strengths': 'Nguvu',
    'credit_conditions': 'Masharti',
    'credit_summary': 'Muhtasari',
    'credit_approve': 'IDHINISHA',
    'credit_conditional': 'MASHARTI',
    'credit_decline': 'KATAA',
    'credit_none_yet': 'Bofya "Fanya Tathmini ya Mkopo" kupata wasifu wako tayari kwa benki.',
    'scan_today_title': 'Skani za Leo',
    'your_status': 'Hali Yako',
    'documents': 'Nyaraka',
    'recent_scans': 'Skani za Hivi Karibuni',
    'see_all': 'Ona Zote',
    'financial_services': 'Huduma za Kifedha',
    'loan_prequal': 'Ustahili wa Mkopo',
    'days_active_short': 'Siku Hai',
    'scan_count_label': 'Jumla ya Skani',
    'litres_30d': 'Lita (siku 30)',
    'fuel_spent_30d': 'Mafuta (siku 30)',
    'registration_complete': 'Usajili Umekamilika',
    'account_active': 'Hai',
    'account_pending': 'Inasubiri',
    'savings_balance': 'Akiba',
    'dues_status': 'Hali ya Michango',
    'current': 'Sawa',
    'eligible_now': 'Unastahili sasa',
    'days_until_eligible': 'siku hadi ustahili (kiwango cha chini siku 90)',
    'complete_label': 'imekamilika',
    'my_money_subtitle': 'Fuatilia matumizi yako kujenga Boda Score imara',
    'cashflow_30d': 'MZUNGUKO WA SIKU 30',
    'est_income': 'Kipato (kilichorekodiwa)',
    'reported_spending': 'Matumizi Yaliyorekodiwa',
    'estimated_surplus': 'Ziada Inayokadiriwa',
    'why_track': 'Kwa Nini Kufuatilia Matumizi?',
    'why_track_desc': 'Benki zinahitaji kuona unapata zaidi ya unachotumia kabla ya kukupa mkopo. Fuatilia mara kwa mara kufungua mikopo mikubwa kwa riba ndogo.',
    'this_month_spending': 'Matumizi ya Mwezi Huu',
    'add': 'Ongeza',
    'credit_profile': 'Wasifu wa Mkopo',
    'what_bank_sees': 'KILE BENKI INACHOONA',
    'no_spending_yet': 'Bado hujarekodi matumizi',
    'no_scans_yet': 'Bado hakuna skani za mafuta',
    'scan_history_title': 'Historia ya Skani za Mafuta',
    'totals_30d': 'Jumla ya Siku 30',
    'sign_out_confirm': 'Ondoka',
    'data_privacy': 'Data & Faragha',
    'view_my_data': 'Ona Data Yangu',
    'view_my_data_desc': 'Ona data yote Chapgo iliyonayo kukuhusu',
    'menu_qr': 'QR Code Yangu',
    // ChapDeliver (Delivery)
    'deliver': 'Tuma',
    'delivery_title': 'ChapDeliver™',
    'delivery_subtitle': 'Uaminifu wa Biashara Mtandao & Usafirishaji wa Mwisho',
    'delivery_coming_soon': 'INAKUJA HIVI KARIBUNI',
    'delivery_coming_soon_desc': 'Moduli ya Awamu ya 3+ — Imeundwa sasa, itazinduliwa baada ya msingi wa Chapgo kuthibitisha mfumo',
    'delivery_planned_features': 'HUDUMA ZILIZOPANGWA',
    'delivery_feat_escrow': 'Malipo ya Amana',
    'delivery_feat_escrow_desc': 'Pesa za mnunuzi huhifadhiwa salama hadi usafirishaji uthibitishwe kwa kuskani QR',
    'delivery_feat_pricing': 'Bei Inayobadilika',
    'delivery_feat_pricing_desc': 'Ada za usafirishaji kulingana na umbali kama Uber na mchanganuo wa wazi',
    'delivery_feat_seller_score': 'Alama ya Muuzaji',
    'delivery_feat_seller_score_desc': 'Beji za uaminifu — tathmini za miamala iliyothibitishwa pekee ndizo zinazohesabika',
    'delivery_feat_tracking': 'Ufuatiliaji wa Moja kwa Moja',
    'delivery_feat_tracking_desc': 'Ufuatiliaji wa GPS wa moja kwa moja kutoka kuchukua hadi kufikisha',
    'delivery_feat_dispute': 'Utatuzi wa Migogoro',
    'delivery_feat_dispute_desc': 'Utatuzi wa saa 24 kwa kutumia ushahidi wa picha',
    'delivery_feat_pindrop': 'Anwani za GPS (Pin-Drop)',
    'delivery_feat_pindrop_desc': 'Weka alama ya GPS na maelezo ya alama za eneo — hakuna haja ya anwani ya posta',
    'delivery_how_it_works': 'JINSI INAVYOFANYA KAZI',
    'delivery_step_1': 'Muuzaji anaweka bidhaa pamoja na bei',
    'delivery_step_2': 'Mnunuzi anaweka pesa kwenye Amana ya ChapPesa',
    'delivery_step_3': 'Dereva wa Chapgo anachukua na kusafirisha bidhaa',
    'delivery_step_4': 'Mnunuzi anaskani QR code kuthibitisha amepokea',
    'delivery_step_5': 'Pesa inatolewa kwa muuzaji na dereva',
    'delivery_regulatory': 'MASHARTI YA KISHERIA',
    'delivery_regulatory_desc': 'Amana inahitaji leseni ya malipo ya BoT au mshirika mwenye leseni. Inapendekezwa kupitia BoT Fintech Regulatory Sandbox (GN 540/2024). Uthibitishaji wa muuzaji unahitaji NIDA API. Data yote lazima izingatie PDPA 2022 na Sheria ya Miamala ya Kielektroniki 2015.',
    'delivery_register_interest': 'Sajili Nia Yangu',
    'delivery_interest_recorded': 'Asante! Tutakujulisha ChapDeliver itakapozinduliwa.',
  };
}
